import pytest
from unittest.mock import patch, MagicMock
import paramiko
from pathlib import Path
import yaml
import shutil

from src.config.settings import Settings
from src.handlers.execution_handler import ExecutionHandler, JobSubmissionResult, ExecutionResult

@pytest.fixture
def detailed_config_file(tmp_path: Path) -> Path:
    """Provides a detailed, hierarchical config file for testing handlers."""
    config_data = {
        "ExecutionHandler": {
            "HpcJobSubmitter": "remote",
            "PostProcessor": "local",
        },
        "paths": {
            "base_directory": "/test/base",
            "local": {
                "simulation_output_dir": "{base_directory}/temp_files/{case_id}/raw_output",
                "final_dicom_dir": "{base_directory}/final_dicom_output/{case_id}",
            },
            "remote": {
                "remote_script_path": "/hpc/scripts",
            },
        },
        "executables": {
            "local": {
                "python": "/usr/bin/python3",
                "raw_to_dicom_script": "{base_directory}/RawToDCM/moqui_raw2dicom.py",
            },
            "remote": {},
        },
        "command_templates": {
            "local": {
                "submit_simulation": "bash /local/run.sh --case-id {case_id} --gpu-id {gpu_id}",
                "post_process": "{python} {raw_to_dicom_script} --input {input_file} --output {output_dir}",
            },
            "remote": {
                "remote_submit_simulation": "sbatch {remote_script_path}/run_moqui.sh --case-id {case_id}",
            },
        },
    }
    config_file = tmp_path / "config.yaml"
    with open(config_file, "w") as f:
        yaml.dump(config_data, f)
    return config_file

@pytest.fixture
def settings(detailed_config_file: Path) -> Settings:
    """Fixture to provide a real Settings instance."""
    return Settings(config_path=detailed_config_file)

@pytest.fixture
def mock_ssh_client() -> MagicMock:
    """Fixture for a mocked SSHClient."""
    mock_ssh = MagicMock(spec=paramiko.SSHClient)
    mock_channel = MagicMock()
    mock_channel.recv_exit_status.return_value = 0
    mock_stdin, mock_stdout, mock_stderr = MagicMock(), MagicMock(), MagicMock()
    mock_stdout.channel = mock_channel
    mock_stdout.read.return_value = b"Submitted batch job 12345"
    mock_stderr.read.return_value = b""
    mock_ssh.exec_command.return_value = (mock_stdin, mock_stdout, mock_stderr)
    mock_ssh.open_sftp.return_value = MagicMock(spec=paramiko.SFTPClient)
    return mock_ssh

# --- Tests for the new, simplified handler methods ---

@patch.object(ExecutionHandler, 'execute_command')
def test_submit_simulation_job_uses_settings_for_remote(mock_execute_command, settings, mock_ssh_client):
    """
    Tests that submit_simulation_job gets a 'remote' command from Settings and executes it.
    """
    # Arrange
    settings.execution_handler["HpcJobSubmitter"] = "remote"
    mock_execute_command.return_value = ExecutionResult(success=True, output="Submitted batch job 12345", error="", return_code=0)
    handler = ExecutionHandler(settings=settings, mode="remote", ssh_client=mock_ssh_client)

    # Expected command is generated by the Settings object using the correct key
    expected_command = settings.get_command("remote_submit_simulation", handler_name="HpcJobSubmitter", case_id="C-REMOTE")
    assert "sbatch" in expected_command # Sanity check

    # Act: Pass the correct command_key
    result = handler.submit_simulation_job(
        handler_name="HpcJobSubmitter",
        command_key="remote_submit_simulation",
        case_id="C-REMOTE"
    )

    # Assert
    mock_execute_command.assert_called_once_with(expected_command)
    assert result.success
    assert result.job_id == "12345"

@patch.object(ExecutionHandler, 'execute_command')
def test_post_process_uses_settings_for_local(mock_execute_command, settings):
    """
    Tests that post_process gets a 'local' command from Settings and executes it.
    """
    # Arrange
    settings.execution_handler["PostProcessor"] = "local"
    handler = ExecutionHandler(settings=settings, mode="local")

    context = {"case_id": "C-LOCAL", "input_file": "/test/input.raw", "output_dir": "/test/output"}
    expected_command = settings.get_command("post_process", handler_name="PostProcessor", **context)
    assert "/usr/bin/python3" in expected_command # Sanity check

    # Act
    handler.post_process(handler_name="PostProcessor", **context)

    # Assert
    mock_execute_command.assert_called_once_with(expected_command, cwd=None)


# --- Tests for the underlying execution logic (still valid) ---

def test_handler_initialization():
    """Test handler initialization requires settings."""
    with pytest.raises(TypeError):
        ExecutionHandler(mode="local") # Missing settings

    mock_settings = MagicMock(spec=Settings)
    handler = ExecutionHandler(settings=mock_settings, mode="local")
    assert handler.mode == "local"
    assert handler.settings is mock_settings

@patch("subprocess.run")
def test_execute_command_local_mode(mock_run):
    """Test raw command execution in 'local' mode."""
    handler = ExecutionHandler(settings=MagicMock(spec=Settings), mode="local")
    handler.execute_command("ls -l")
    mock_run.assert_called_once_with("ls -l", shell=True, check=True, capture_output=True, text=True, cwd=None)

def test_execute_command_remote_mode(mock_ssh_client):
    """Test raw command execution in 'remote' mode."""
    handler = ExecutionHandler(settings=MagicMock(spec=Settings), mode="remote", ssh_client=mock_ssh_client)
    handler.execute_command("ls -l", cwd="/tmp")
    mock_ssh_client.exec_command.assert_called_once_with("cd /tmp && ls -l")

@patch("shutil.copy")
def test_upload_file_local_mode(mock_copy):
    """Test file upload (copy) in 'local' mode."""
    handler = ExecutionHandler(settings=MagicMock(spec=Settings), mode="local")
    handler.upload_file("a.txt", "b.txt")
    mock_copy.assert_called_once_with("a.txt", "b.txt")